import {
  BreadcrumbNav,
  Bullets,
  Callout,
  DocHeader,
  DocSection,
  InlineCode,
  RelatedDocs,
  ScreenshotFrame,
} from '@/components/marketing/docs-ui';
import { seoPage } from '@/lib/seo';

export const metadata = seoPage({
  path: '/docs/analytics',
  title: 'Analytics, usage & KPI metrics',
  description:
    'Monitor message volume, active visitor sessions, popular questions, response latency, token consumption, and monthly subscription quotas in WebChat AI.',
});

export default function AnalyticsDocPage() {
  return (
    <div className="flex flex-col gap-8">
      <BreadcrumbNav
        items={[
          { label: 'Documentation', href: '/docs' },
          { label: 'Manage' },
          { label: 'Analytics' },
        ]}
      />

      <DocHeader
        breadcrumb="Manage / Analytics & usage"
        title="Analytics & telemetry"
        lede="Gain deep operational visibility into your AI assistant traffic. Track conversation volume, recurring visitor queries, token consumption costs, latency histograms, and monthly plan limits."
      />

      <ScreenshotFrame
        src="/docs-assets/screenshots/analytics.png"
        alt="WebChat AI Analytics Dashboard showing KPIs, message trends, popular questions, and token usage"
        caption="WebChat AI Analytics dashboard overview displaying message volume trends, response times, and query metrics."
      />

      <DocSection
        id="kpi-metrics"
        title="Core KPI telemetry"
        description="Headline metrics tracked across your entire assistant fleet or scoped per assistant."
      >
        <p className="text-sm leading-relaxed text-muted-foreground">
          The top of the Analytics view displays five critical operational health indicators,
          comparing the selected date range (<InlineCode>7d</InlineCode>,{' '}
          <InlineCode>30d</InlineCode>, or <InlineCode>90d</InlineCode>) against the preceding
          period:
        </p>

        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          <div className="rounded-lg border border-border/60 bg-card p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Total Messages
            </p>
            <p className="mt-2 text-2xl font-bold tracking-tight text-foreground">Message Volume</p>
            <p className="mt-1 text-xs text-muted-foreground">
              Total inbound questions from visitors and outbound answers generated by your
              assistants.
            </p>
          </div>
          <div className="rounded-lg border border-border/60 bg-card p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Conversations
            </p>
            <p className="mt-2 text-2xl font-bold tracking-tight text-foreground">
              Unique Sessions
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Distinct visitor conversation threads initiated through the embedded widget or test
              harness.
            </p>
          </div>
          <div className="rounded-lg border border-border/60 bg-card p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Response Time
            </p>
            <p className="mt-2 text-2xl font-bold tracking-tight text-foreground">
              Average Latency
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Mean duration in seconds across retrieval, prompt assembly, and token streaming.
            </p>
          </div>
          <div className="rounded-lg border border-border/60 bg-card p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Token Cost
            </p>
            <p className="mt-2 text-2xl font-bold tracking-tight text-foreground">
              Estimated Usage
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Calculated consumption of input (prompt) and output (completion) tokens across model
              providers.
            </p>
          </div>
          <div className="rounded-lg border border-border/60 bg-card p-4">
            <p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Visitor Feedback
            </p>
            <p className="mt-2 text-2xl font-bold tracking-tight text-foreground">
              Satisfaction Rating
            </p>
            <p className="mt-1 text-xs text-muted-foreground">
              Percentage of positive ratings (thumbs up) and average 1-5 star user sentiment scores.
            </p>
          </div>
        </div>
      </DocSection>

      <DocSection
        id="popular-questions"
        title="Popular & recurring questions"
        description="Identify what visitors ask most frequently and detect content gaps."
      >
        <p className="text-sm leading-relaxed text-muted-foreground">
          WebChat AI aggregates incoming visitor questions by normalized question text, ranking top
          inquiries by ask frequency and satisfaction rating. The{' '}
          <strong className="font-medium text-foreground">Popular Questions</strong> table reveals:
        </p>

        <Bullets
          items={[
            <>
              <strong className="font-medium text-foreground">Frequency Rank:</strong> The exact
              number of times visitors have asked the question during the selected period.
            </>,
            <>
              <strong className="font-medium text-foreground">Question Content:</strong> The
              normalized, trimmed visitor query text.
            </>,
            <>
              <strong className="font-medium text-foreground">Average Satisfaction:</strong> Visitor
              feedback scores on answers provided for this inquiry, highlighting areas where
              knowledge may need expansion.
            </>,
          ]}
        />

        <Callout variant="tip" title="Optimizing Documentation from Analytics">
          If a specific question ranks in your top 5 queries with a lower satisfaction score, it
          typically indicates your source website or documents lack a direct explanation. Uploading
          an FAQ document or updating that web page immediately resolves the gap.
        </Callout>
      </DocSection>

      <DocSection
        id="plan-quotas"
        title="Quotas & monthly limits"
        description="Understanding plan consumption, rate limits, and billing tiers."
      >
        <p className="text-sm leading-relaxed text-muted-foreground">
          Each subscription tier enforces predefined monthly quotas to protect system stability and
          predictable operating costs:
        </p>

        <div className="overflow-x-auto rounded-lg border border-border/60">
          <table className="w-full text-left text-sm">
            <caption className="sr-only">Plan limits and quotas</caption>
            <thead className="bg-muted/50 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              <tr>
                <th scope="col" className="px-4 py-3">
                  Plan Tier
                </th>
                <th scope="col" className="px-4 py-3">
                  Chatbots
                </th>
                <th scope="col" className="px-4 py-3">
                  Crawled Pages
                </th>
                <th scope="col" className="px-4 py-3">
                  Monthly Messages
                </th>
                <th scope="col" className="px-4 py-3">
                  File Uploads
                </th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/60 text-xs">
              <tr>
                <td className="px-4 py-3 font-semibold text-foreground">Free</td>
                <td className="px-4 py-3 font-mono">1</td>
                <td className="px-4 py-3 font-mono">20 URLs</td>
                <td className="px-4 py-3 font-mono">50 / month</td>
                <td className="px-4 py-3 font-mono">10 MB / batch (max 5)</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-semibold text-foreground">Starter</td>
                <td className="px-4 py-3 font-mono">3</td>
                <td className="px-4 py-3 font-mono">200 URLs</td>
                <td className="px-4 py-3 font-mono">2,000 / month</td>
                <td className="px-4 py-3 font-mono">10 MB / batch (max 5)</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-semibold text-foreground">Pro</td>
                <td className="px-4 py-3 font-mono">10</td>
                <td className="px-4 py-3 font-mono">1,000 URLs</td>
                <td className="px-4 py-3 font-mono">10,000 / month</td>
                <td className="px-4 py-3 font-mono">10 MB / batch (max 5)</td>
              </tr>
              <tr>
                <td className="px-4 py-3 font-semibold text-foreground">Enterprise</td>
                <td className="px-4 py-3 font-mono">Custom</td>
                <td className="px-4 py-3 font-mono">Custom</td>
                <td className="px-4 py-3 font-mono">Custom</td>
                <td className="px-4 py-3 font-mono">Custom limits</td>
              </tr>
            </tbody>
          </table>
        </div>

        <p className="mt-3 text-xs text-muted-foreground">
          When an assistant reaches its monthly query limit, the widget returns{' '}
          <InlineCode>429 MESSAGE_LIMIT_REACHED</InlineCode> with a polite notice to the visitor.
          Account owners can upgrade anytime in the Billing panel to instantly restore query
          capacity.
        </p>
      </DocSection>

      <RelatedDocs
        links={[
          {
            title: 'Conversations & visitor logs',
            href: '/docs/conversations',
            description: 'Drill into individual conversation transcripts and source citations.',
          },
          {
            title: 'REST API reference',
            href: '/docs/api',
            description: 'Query analytics endpoints programmatically for automated reporting.',
          },
          {
            title: 'Troubleshooting guide',
            href: '/docs/troubleshooting',
            description: 'Learn how to handle 429 quota exhaustion or high latency errors.',
          },
        ]}
      />
    </div>
  );
}
